window.__RECRUIT_DATA__ = {
  "meta": {
    "title": "2027届秋招信息池",
    "updatedAt": "2026-09-15",
    "owner": "刘峻豪",
    "scope": "仅面向2027届毕业生，已排除社会招聘",
    "sources": [
      "国务院国资委人事招聘专栏 http://www.sasac.gov.cn",
      "中国公共招聘网 http://job.mohrss.gov.cn",
      "国聘网 https://www.iguopin.com",
      "国家大学生就业服务平台(24365) https://www.ncss.cn",
      "各集团招聘官网 / 大厂校招官网"
    ],
    "note": "deadline 为空表示官方公告未公布截止时间（招满即止或待公告），未做编造；带“预测”字样为往年节奏推测，以官网为准。"
  },
  "records": [
    {
      "id": "bytedance-2027",
      "org": "字节跳动",
      "position": "研发 / 产品 / 运营 / 设计 / 市场 / 职能支持 / 销售 / 游戏策划（含AI全栈工程师、AI Agent开发）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "2027-05-31",
      "deadlineNote": "全年滚动招聘，岗位招满即下架（网申开放至2027-05-31）",
      "source": "字节跳动招聘官网 jobs.bytedance.com / 中公网校",
      "publishedAt": "2026-08-03",
      "url": "https://jobs.bytedance.com/campus",
      "target": "2027届（2026.9-2027.8毕业）"
    },
    {
      "id": "tencent-2027",
      "org": "腾讯",
      "position": "技术类 / 产品类 / 设计类 / 市场类 / 职能类（含青云计划、AI全栈工程师、AIGC艺术创作）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止；官方建议8-10月集中面试与录用，尽早投递",
      "source": "腾讯招聘官网 join.qq.com / 光明网",
      "publishedAt": "2026-08-11",
      "url": "https://join.qq.com",
      "target": "2027届（2026.1-2027.12毕业）"
    },
    {
      "id": "alibaba-2027",
      "org": "阿里巴巴",
      "position": "算法 / 研发 / 芯片 / 产品 / 游戏 / 运营 / 商务拓展（淘天集团、阿里云、阿里星顶尖人才计划）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "2026-11-30",
      "deadlineNote": "淘天集团截止11月30日，集团整体招满即止",
      "source": "阿里巴巴校园招聘官网 / 网易",
      "publishedAt": "2026-08-05",
      "url": "https://talent.alibaba.com",
      "target": "2027届（2026.11.1-2027.10.31毕业）"
    },
    {
      "id": "jd-2027",
      "org": "京东",
      "position": "采销 / 物流 / 技术 / 产品 / 运营 / 设计",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "2026-11-30",
      "deadlineNote": "网申8.3-11.30，建议尽早投递",
      "source": "京东校招官网 campus.jd.com",
      "publishedAt": "2026-08-03",
      "url": "https://campus.jd.com",
      "target": "2027届本科、硕博"
    },
    {
      "id": "baidu-2027",
      "org": "百度",
      "position": "AI大模型 / 自动驾驶 / 算法 / 研发（AIDU计划，AI岗占比超90%）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "长期招聘",
      "source": "百度招聘官网 / 今日头条",
      "publishedAt": "2026-07-09",
      "url": "https://talent.baidu.com/jobs",
      "target": "2027届"
    },
    {
      "id": "bilibili-2027",
      "org": "哔哩哔哩（B站）",
      "position": "技术类 / 产品运营类 / 内容类 / 市场营销类 / 项目管理类 / 大职能类 / 游戏类（B-UP顶尖技术人才项目）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止",
      "source": "B站招聘 / 网易",
      "publishedAt": "2026-08-03",
      "url": "https://campus.bilibili.com",
      "target": "2027届（2026.9.1-2027.8.31毕业）"
    },
    {
      "id": "ant-2027",
      "org": "蚂蚁集团",
      "position": "技术岗（占比80%，超80% AI相关）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止",
      "source": "蚂蚁集团招聘 / 腾讯新闻",
      "publishedAt": "2026-08-10",
      "url": "https://talent.antgroup.com",
      "target": "2027届"
    },
    {
      "id": "xiaomi-2027",
      "org": "小米",
      "position": "技术 / 产品 / 设计 / 供应链 / 职能等多方向（全球校招）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "2026-12-31",
      "deadlineNote": "网申2026.8.10-12.31，招满即止",
      "source": "小米招聘官网 hr.xiaomi.com",
      "publishedAt": "2026-08-05",
      "url": "https://hr.xiaomi.com",
      "target": "2027届（2026.9.1-2027.8.31毕业）"
    },
    {
      "id": "meituan-2027",
      "org": "美团",
      "position": "技术 / 产品 / 运营 / 职能等多方向",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "2026-10-31",
      "deadlineNote": "网申8.17-10.31，部分岗位招满即提前结束；9月起面试",
      "source": "美团校招官网 zhaopin.meituan.com / 南京本地宝",
      "publishedAt": "2026-08-17",
      "url": "https://zhaopin.meituan.com/web/campus",
      "target": "2027届"
    },
    {
      "id": "netease-2027",
      "org": "网易",
      "position": "应届生 / 精英实习生（技术、产品、设计、游戏等）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止",
      "source": "网易校园招聘 campus.163.com",
      "publishedAt": "2026-08-12",
      "url": "https://campus.163.com",
      "target": "2027届"
    },
    {
      "id": "huawei-2027",
      "org": "华为",
      "position": "2027届顶尖AI人才专项行动 / 天才少年（芯片、AI大模型）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "长期招聘",
      "source": "华为招聘官网 career.huawei.com",
      "publishedAt": "2026-07-15",
      "url": "https://career.huawei.com",
      "target": "2027届"
    },
    {
      "id": "lenovo-2027",
      "org": "联想",
      "position": "技术 / 产品与销售 / 供应链 / 设计 / 职能方向",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "2026-11-13",
      "deadlineNote": "",
      "source": "联想招聘 / 网易",
      "publishedAt": "2026-08-05",
      "url": "https://talent.lenovo.com.cn",
      "target": "2027届本科及以上"
    },
    {
      "id": "cambricon-2027",
      "org": "寒武纪",
      "position": "芯片类 / 软件类 / 职能与研发支持类",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止",
      "source": "寒武纪招聘 / 网易",
      "publishedAt": "2026-08-10",
      "url": "https://www.cambricon.com",
      "target": "2027届（2026.9-2027.8毕业）"
    },
    {
      "id": "honor-2027",
      "org": "荣耀",
      "position": "多方向（全球校招）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "2026-09-30",
      "deadlineNote": "",
      "source": "荣耀校招 / 南京本地宝",
      "publishedAt": "2026-08-12",
      "url": "https://www.honor.com/cn/career/",
      "target": "2027届"
    },
    {
      "id": "chinatelecom-2027",
      "org": "中国电信",
      "position": "市场 / 销售与服务 / 产品 / 企业信息化 / 网发建设 / 网络维护 / 研发 / 产数 / 综合支撑（含优才计划）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "8月底启动网申，持续至11月，各省分公司截止不同，招满即止（以分公司公告为准）",
      "source": "中国电信招贤纳士专栏 / 高顿",
      "publishedAt": "2026-08-24",
      "url": "http://www.chinatelecom.com.cn/zp/",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "cnnc-2027",
      "org": "中核集团",
      "position": "核科技 / 工程建筑 / 地质矿产 / 机械控制 / 医药学类 / 财会 / 经管 / 人文社科（星原计划、核星计划）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "网申→测评→笔面试→offer，截止待官网",
      "source": "中核人才招聘网 / 清华就业",
      "publishedAt": "2026-08-14",
      "url": "https://www.cnnc.com.cn",
      "target": "2027届博士、硕士、本科"
    },
    {
      "id": "coamc-2027",
      "org": "中国东方资产管理",
      "position": "2027年度校园招聘（金融类多岗位）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-09-18",
      "deadlineNote": "",
      "source": "国聘网 / 华图汇总",
      "publishedAt": "2026-08-17",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "picc-2027",
      "org": "中国人民保险（人保）",
      "position": "2027年度校园招聘（保险 / 科技 / 职能多岗位）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2027-04-25",
      "deadlineNote": "8月1日起",
      "source": "国聘网 / 华图汇总",
      "publishedAt": "2026-08-01",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "everbright-2027",
      "org": "光大证券",
      "position": "2027校园招聘（金融 / 研究 / 科技岗）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-09-06",
      "deadlineNote": "",
      "source": "国聘网 / 华图汇总",
      "publishedAt": "2026-08-10",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "zhongtai-2027",
      "org": "中泰证券",
      "position": "2027秋季校园招聘",
      "category": "央国企",
      "batch": "提前批",
      "deadline": "2026-08-06",
      "deadlineNote": "已截止（参考公告）",
      "source": "国聘网 / 华图汇总",
      "publishedAt": "2026-08-01",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "pinganbank-2027",
      "org": "平安银行",
      "position": "2027秋季校园招聘（科技 / 业务 / 职能）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-11-06",
      "deadlineNote": "8月10日起",
      "source": "国聘网 / 华图汇总",
      "publishedAt": "2026-08-10",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "sgcc-2027",
      "org": "国家电网",
      "position": "2027第一批（电工类为主，覆盖市局县局；含电子信息/财会/管理类）",
      "category": "央国企",
      "batch": "一批（未发布）",
      "deadline": "",
      "deadlineNote": "提前批 9 月发布、10 月中旬国调网调专项；一批预计 11 月中旬网申、12 月上旬笔试（预测，以官网为准）",
      "source": "国家电网人力资源招聘平台 zhaopin.sgcc.com.cn",
      "publishedAt": "",
      "url": "https://zhaopin.sgcc.com.cn",
      "target": "2027届（电工类专科及以上，其他本科及以上）"
    },
    {
      "id": "chnenergy-2027",
      "org": "国家能源集团",
      "position": "2027校园招聘（电力电气 / 煤炭 / 化工机械数字化 / 职能经管）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-07",
      "deadlineNote": "统招网报 9.2-10.7；笔试 10.25；直招 9.19 截止",
      "source": "国家能源集团招聘 zhaopin.chnenergy.com.cn",
      "publishedAt": "2026-09-02",
      "url": "http://zhaopin.chnenergy.com.cn",
      "target": "2027届"
    },
    {
      "id": "china-railway-2027",
      "org": "中国铁路",
      "position": "2027校园招聘（各铁路局，仅铁路人才网发布）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "各局时间不同；集中公告预计2026年10月31日前后（预测，以铁路人才网为准）",
      "source": "中国铁路人才招聘网 rczp.china-railway.com.cn",
      "publishedAt": "",
      "url": "https://rczp.china-railway.com.cn",
      "target": "2027届"
    },
    {
      "id": "cnpc-2027",
      "org": "中石油",
      "position": "2027校园招聘（正式批，油气勘探开发/炼化/新能源/数字化/经管等多方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-15",
      "deadlineNote": "官方确认2026秋招9.9启动，报名截止2026-10-15 23:59（中国石油高校毕业生招聘平台为唯一渠道）",
      "source": "中国石油网 cnpc.com.cn / 中国石油高校毕业生招聘平台 zhaopin.cnpc.com.cn",
      "publishedAt": "2026-09-09",
      "url": "https://zhaopin.cnpc.com.cn",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "sinopec-2027",
      "org": "中石化",
      "position": "2027校园招聘（正式批）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "预计 2026 年 9 月下旬（约 9.25）开启网申；笔试 11 月中下旬（预测，以官网为准）",
      "source": "中石化招聘官网",
      "publishedAt": "",
      "url": "https://job.sinopec.com",
      "target": "2027届"
    },
    {
      "id": "casic-2027",
      "org": "航天科工",
      "position": "2027校园招聘（正式批，研发 / 技术 / 职能）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届秋季招聘于2026-09-02全面启动（正式批），招满即止；提前批(8.24)已截止",
      "source": "国务院国资委人事招聘专栏 / 航天科工校招",
      "publishedAt": "2026-09-02",
      "url": "http://casicjob.iguopin.com",
      "target": "2027届（理工科为主）"
    },
    {
      "id": "cetc-2027",
      "org": "中国电科",
      "position": "2027校园招聘（电子 / 计算机 / 机械 / 兵器类研发岗）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "预计2026年8月左右开启（预测）",
      "source": "中国电科官网 / 国聘网",
      "publishedAt": "",
      "url": "https://www.cetc.com.cn",
      "target": "2027届（研发岗硕博为主）"
    },
    {
      "id": "inspur-2027",
      "org": "浪潮集团",
      "position": "2027届校园招聘（提前批，技术 / 研发方向）",
      "category": "央国企",
      "batch": "提前批",
      "deadline": "",
      "deadlineNote": "招满即止",
      "source": "浪潮招聘 / 高校就业网",
      "publishedAt": "2026-08-05",
      "url": "https://www.inspur.com",
      "target": "2027届"
    },
    {
      "id": "dfmc-2027",
      "org": "东风汽车（东风奕派）",
      "position": "2027全球校园招聘（技术 / 研发 / 设计 / 职能）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止",
      "source": "东风招聘 / 高校就业网",
      "publishedAt": "2026-08-05",
      "url": "https://www.dfmc.com.cn",
      "target": "2027届"
    },
    {
      "id": "unigroup-2027",
      "org": "紫光国芯",
      "position": "2027校园招聘（芯片 / 研发方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止",
      "source": "紫光国芯招聘 / 高校就业网",
      "publishedAt": "2026-08-05",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "kuaishou-2027",
      "org": "快手",
      "position": "算法类 / 工程类 / 产品类 / 运营类 / 游戏类 / 设计类 / 市场类 / 销售类 / 职能类 / 战略分析类 / 项目管理类（含快Star顶尖技术人才计划、AI全栈开发 / Agent开发）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "网申8月12日起，全年持续开放投递，招满即止",
      "source": "快手校招官网 campus.kuaishou.cn / 国科大就业网",
      "publishedAt": "2026-08-12",
      "url": "https://campus.kuaishou.cn",
      "target": "2027届（2026.11-2027.10毕业）"
    },
    {
      "id": "xiaohongshu-2027",
      "org": "小红书",
      "position": "搜索 / 推荐 / 广告 / 基座大模型 / AI Agent / AI Infra / AI Coding / 多模态 / 语音 / 引擎架构 / 多媒体 / 安全 / 云原生 / 存储数据库（REDstar顶尖人才计划）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "8月25日启动，招满即止",
      "source": "小红书招聘 / 江南都市报",
      "publishedAt": "2026-08-25",
      "url": "https://campus.xiaohongshu.com",
      "target": "2027届（含毕业两年内技术人才）"
    },
    {
      "id": "chinamobile-2027",
      "org": "中国移动",
      "position": "技术类（通信网络 / 云网 / AI大模型算法 / AI架构师） / 市场类 / 综合类（财务 / 法务 / 人力），金种子计划",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-08",
      "deadlineNote": "正式批网申 9 月初-10.8；笔试 10 月下旬（四川 10.24）",
      "source": "中国移动招聘官网 job.10086.cn",
      "publishedAt": "2026-09-02",
      "url": "https://job.10086.cn",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "chinaunicom-2027",
      "org": "中国联通",
      "position": "新苗计划：AI研发 / 网络安全 / 量子通信 / 网络技术 / 算网 / 数据分析 / 测试开发 / 解决方案 / 产品经理等",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-09-22",
      "deadlineNote": "网申窗口约8.25-9.22（新苗计划），招满即止；11月上旬笔试（以官网为准）",
      "source": "中国联通官网(人力资源专区) / 牛企直聘(企业公众号)",
      "publishedAt": "2026-08-27",
      "url": "https://www.chinaunicom.com.cn",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "pinduoduo-2027",
      "org": "拼多多",
      "position": "云弧计划（大模型算法 / AI Infra）/ 服务端 / 算法 / 客户端 / 前端 / 数据分析 / 安全 / AI Agent；产品·市场·运营·视觉·语言·综合管培（含视频创意制作）",
      "category": "互联网大厂",
      "batch": "提前批",
      "deadline": "2026-08-23",
      "deadlineNote": "提前批已截止（2026-08-23）；云弧计划可随常规秋招各批次重复投递，正式批时间待官网确认",
      "source": "拼多多校招官网 careers.pddglobalhr.com / 牛客·武大就业网",
      "publishedAt": "2026-07-06",
      "url": "https://careers.pddglobalhr.com/campus",
      "target": "2027届（2026.9-2027.8毕业）"
    },
    {
      "id": "vivo-2027",
      "org": "vivo",
      "position": "算法 / 软件 / 硬件 / 通信 / 测试 / 营销 / 市场 / 设计 / 产品运营 / 供应链（10大类别250+方向）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "2026-09-15",
      "deadlineNote": "网申即日起-9月15日12:00；9月20-24日线下面试",
      "source": "vivo招聘官网 hr-campus.vivo.com / 中国科大就业网",
      "publishedAt": "2026-09-01",
      "url": "https://hr-campus.vivo.com/",
      "target": "2027届（2026.8-2027.7毕业）"
    },
    {
      "id": "horizon-2027",
      "org": "地平线",
      "position": "算法 / 芯片 / 软件 / 硬件 / 测试 / 业务拓展（智能驾驶与机器人，物理AI）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "2026-10-30",
      "deadlineNote": "网申8.10-10.30；9月1日空中宣讲（多平台直播）",
      "source": "地平线招聘 / 北京大学就业信息网",
      "publishedAt": "2026-08-10",
      "url": "https://wecruit.hotjob.cn/SU62d915040dcad43c775ec12c/mc/position/campus?channelId=149807",
      "target": "2027届（2026.9.1-2027.8.31毕业）"
    },
    {
      "id": "didi-2027",
      "org": "滴滴",
      "position": "工程 / 算法 / 机器人 / 产品 / 安全技术 / 运营 / 数据 / 商分 / 金融业务",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止",
      "source": "滴滴校招官网 campus.didiglobal.com",
      "publishedAt": "2026-08-13",
      "url": "http://campus.didiglobal.com",
      "target": "2027届（2026.9-2027.8毕业）"
    },
    {
      "id": "cmb-tech-2027",
      "org": "招商银行·招银网络科技",
      "position": "2027秋季校园招聘（科技 / 研发方向，金融科技岗）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-09-20",
      "deadlineNote": "第一批网申7.30-9.3 18时已截止；第二批至9.20 18时；技术测评9.21，面试9.29-10.20",
      "source": "招银网络科技招聘 / 华北电力大学就业指导中心",
      "publishedAt": "2026-07-30",
      "url": "https://career.cmbchina.com",
      "target": "2027届"
    },
    {
      "id": "icbc-2027",
      "org": "中国工商银行",
      "position": "2027年度校园招聘（总行及境内分行，管培 / 科技菁英 / 客户经理等）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-08",
      "deadlineNote": "网上报名 2026.9.4-10.8；笔试 10 月下旬",
      "source": "工商银行招聘官网 job.icbc.com.cn",
      "publishedAt": "2026-09-04",
      "url": "https://job.icbc.com.cn",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "abc-2027",
      "org": "中国农业银行",
      "position": "2027年度校园招聘（总行 / 境内分行 / 子公司，管培 / 科技英才等）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-08",
      "deadlineNote": "报名即日起-10.8 24时；笔试 10 月下旬或 11 月上旬",
      "source": "农业银行招聘官网 career.abchina.com.cn",
      "publishedAt": "2026-09-04",
      "url": "https://career.abchina.com.cn",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "boc-2027",
      "org": "中国银行",
      "position": "2027年全球校园招聘（总行 / 境内分行 / 海外及综合经营公司）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-09",
      "deadlineNote": "报名截止 2026.10.9 24点；笔试 10 月中下旬",
      "source": "中国银行校招 campus.chinahr.com/pages/2027-boc",
      "publishedAt": "2026-09-03",
      "url": "https://www.boc.cn",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "ccb-2027",
      "org": "中国建设银行",
      "position": "2027年度校园招聘（总行直属机构 / 各省市分行）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-08",
      "deadlineNote": "报名截止 2026.10.8 24点；笔试 10 月底",
      "source": "建设银行招聘官网 job.ccb.com",
      "publishedAt": "2026-09-04",
      "url": "http://job.ccb.com",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "bocom-2027",
      "org": "交通银行",
      "position": "2027届校园招聘（总行 / 境内分行 / 子公司，科技/业务/职能）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-12",
      "deadlineNote": "网申2026.9.5-10.12；笔试各分行自行组织（以官网为准）",
      "source": "交行招聘官网 job.bankcomm.com / 银行招聘网",
      "publishedAt": "2026-09-05",
      "url": "https://job.bankcomm.com",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "psbc-2027",
      "org": "中国邮政储蓄银行",
      "position": "2027届校园招聘（总行 / 各分行 / 控股子公司，金融科技/管培/基层）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-09-30",
      "deadlineNote": "网申2026.9.1-9.30（六大行截止最早）；笔试2026.10.26（以官网为准）",
      "source": "邮储银行招聘官网 / 银行招聘网",
      "publishedAt": "2026-09-01",
      "url": "https://www.psbc.com",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "chinanuclear-2027",
      "org": "中国核电",
      "position": "2027届校园招聘（国企，中核集团旗下）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止（以官网为准）",
      "source": "国聘网 / 中国核电招聘",
      "publishedAt": "2026-09-05",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "citicbank-2027",
      "org": "中信银行",
      "position": "2027年校园招聘（科技 / 业务 / 职能）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止（以官网为准）",
      "source": "国聘网 / 中信银行招聘",
      "publishedAt": "2026-09-05",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "norinco-2027",
      "org": "中国兵器集团",
      "position": "2027届全球校园招聘",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止（以官网为准）",
      "source": "国聘网",
      "publishedAt": "2026-09-05",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "faw-2027",
      "org": "中国一汽",
      "position": "2027届校园招聘",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止（以官网为准）",
      "source": "国聘网 / 中国一汽招聘",
      "publishedAt": "2026-09-05",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "cccc-2027",
      "org": "中交集团",
      "position": "2027届全球校园招聘",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止（以官网为准）",
      "source": "国聘网",
      "publishedAt": "2026-09-05",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "changan-2027",
      "org": "长安汽车",
      "position": "2027全球校园招聘",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止（以官网为准）",
      "source": "国聘网 / 长安汽车招聘",
      "publishedAt": "2026-09-05",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "crland-2027",
      "org": "华润置地",
      "position": "2027届校园招聘",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止（以官网为准）",
      "source": "国聘网 / 华润置地招聘",
      "publishedAt": "2026-09-05",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "cmsk-2027",
      "org": "招商蛇口",
      "position": "2027届校园招聘",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止（以官网为准）",
      "source": "国聘网 / 招商蛇口招聘",
      "publishedAt": "2026-09-05",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "citic-group-2027",
      "org": "中信集团",
      "position": "2027年度校园招聘（集团总部管理培训生 / 综合金融 / 先进智造 / 先进材料 / 新消费 / 新型城镇化多方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-08",
      "deadlineNote": "网申 2026.9.1-10.8 24点；笔试/面试以官网为准",
      "source": "中信集团招聘官网 job.citic.com / 北京大学就业信息网",
      "publishedAt": "2026-09-01",
      "url": "https://job.citic.com",
      "target": "2027届（2027.7.31前取得学历学位的硕博为主，含2026.1-2027.7归国留学生）"
    },
    {
      "id": "avic-2027",
      "org": "中国航空工业集团",
      "position": "2027届校园招聘（研发 / 技术 / 职能等多方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招于2026-09-01正式启动，招满即止（以官网为准）",
      "source": "国务院国资委人事招聘专栏 / 航空工业集团官网",
      "publishedAt": "2026-09-01",
      "url": "https://www.avic.com.cn",
      "target": "2027届（理工科为主）"
    },
    {
      "id": "avic-shenfei-2027",
      "org": "航空工业沈飞",
      "position": "2027届校园招聘（航空研发 / 技术 / 制造方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招于2026-09-01正式启动，招满即止（以官网为准）",
      "source": "国务院国资委人事招聘专栏",
      "publishedAt": "2026-09-01",
      "url": "https://www.avic.com.cn",
      "target": "2027届（理工科为主）"
    },
    {
      "id": "ct-quantum-2027",
      "org": "中电信量子集团",
      "position": "2027校园招聘（量子通信 / 网络安全 / 研发方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027校园招聘于2026-09-02正式启动，招满即止",
      "source": "国务院国资委人事招聘专栏 / 中国电信招聘专栏",
      "publishedAt": "2026-09-02",
      "url": "https://www.chinatelecom.com.cn/zp/",
      "target": "2027届"
    },
    {
      "id": "sdic-2027",
      "org": "国投集团（国家开发投资集团）",
      "position": "2027届校园招聘（集团管培生 / 电力 / 港口 / 生物 / 智能科技 / 金融 / 投资等多方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "网申截止以各招聘单位发布岗位为准，招满即止（以官网为准）",
      "source": "国聘网 sdic.iguopin.com / 北京大学就业信息网",
      "publishedAt": "2026-09-06",
      "url": "https://sdic.iguopin.com",
      "target": "2027届（含2026届未就业）"
    },
    {
      "id": "norinco-208-2027",
      "org": "中国兵器工业第二〇八研究所",
      "position": "2027届高校精英招募（研发 / 技术方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届高校精英招募于2026-09-03发布，招满即止",
      "source": "国务院国资委人事招聘专栏",
      "publishedAt": "2026-09-03",
      "url": "https://www.norincogroup.com.cn",
      "target": "2027届（理工科为主）"
    },
    {
      "id": "chinapost-2027",
      "org": "中国邮政集团",
      "position": "2027届校园招聘（寄递物流 / 金融 / 信息技术 / 综合管理多方向，覆盖全国各级网点）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-31",
      "deadlineNote": "集团统招正式批9月1日发布全国公告，网申至10月31日；全国统一笔试11月中旬（以官网为准）",
      "source": "中国邮政招聘官网 zhaopin.chinapost.com.cn / 国聘网",
      "publishedAt": "2026-09-01",
      "url": "https://zhaopin.chinapost.com.cn",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "cscec-2027",
      "org": "中国建筑（中建集团）",
      "position": "2027届校园招聘（工程技术 / 设计研发 / 商务运营 / 金融投资 / 海外业务，八大局及专业公司）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027秋招预计9月启动网申（先集团统一在线测评、后投简历）；具体截止以官网为准",
      "source": "中国建筑校园招聘官网 recruit.cscec.com / 高校就业网",
      "publishedAt": "2026-09-01",
      "url": "https://recruit.cscec.com",
      "target": "2027届本科及以上"
    },
    {
      "id": "casic-23-2027",
      "org": "航天科工二院二十三所",
      "position": "2027届校园招聘（电子 / 通信 / 雷达 / 计算机 / 控制 / 材料 / 机械，北京为主）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招于2026-09-01开启，招满即止",
      "source": "国务院国资委人事招聘专栏 / 国聘网",
      "publishedAt": "2026-09-01",
      "url": "https://www.iguopin.com",
      "target": "2027届（理工科为主）"
    },
    {
      "id": "cosco-seafarer-2027",
      "org": "中远海运船员公司",
      "position": "2027届航海类校园招聘（航海技术 / 轮机工程等船员岗位）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届航海类校招于2026-09-01开启，招满即止",
      "source": "国务院国资委人事招聘专栏 / 国聘网",
      "publishedAt": "2026-09-01",
      "url": "https://www.iguopin.com",
      "target": "2027届（航海技术/轮机工程等）"
    },
    {
      "id": "mihoyo-2027",
      "org": "米哈游",
      "position": "2027届校园招聘（程序&技术类 / 美术&表现类 / 产品策划类 / 质量管理类 / 运营类 / 市场&商务类 / 综合类 / 国际化类，含AI研发）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027秋招正式批已开启（约8月初启动），网申招满即止；第三方便民信息显示窗口约至2026-10-01（以官网为准）",
      "source": "米哈游招聘公众号 / 牛客 / 牛企直聘",
      "publishedAt": "2026-08-05",
      "url": "https://jobs.mihoyo.com",
      "target": "2027届（2026.9-2027.8毕业）"
    },
    {
      "id": "papergames-2027",
      "org": "叠纸游戏",
      "position": "2027届秋季校园招聘（技术研发类 / 策划类 / 美术类 / 动画CG类 / 市场运营类 / 游戏音频类 / 职能支持类）",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "2026-10-31",
      "deadlineNote": "网申启动即日起，投递截止2026-10-31；笔试即日起，面试8月中旬起，Offer 9月中旬起发放",
      "source": "叠纸游戏招聘公众号 / 牛企直聘",
      "publishedAt": "2026-08-04",
      "url": "https://career.papegames.com/campus",
      "target": "2027届（2026.9-2027.8毕业）"
    },
    {
      "id": "swhy-2027",
      "org": "申万宏源",
      "position": "2027届秋季校园招聘（投行 / 投资交易 / 资产管理 / 财富管理 / 机构业务 / 金融科技 / 合规风控 / 运营财务 / 党群职能，含分支机构财富顾问岗）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-25",
      "deadlineNote": "网申&测评截止2026-10-25 23:59；笔试面试2026-11月起；实习体验12月起；录用2027年1月起",
      "source": "申万宏源证券招聘公众号 / 高校就业网",
      "publishedAt": "2026-08-25",
      "url": "http://www.swhysc.com",
      "target": "2027届（境内2027.1-7毕业，境外2026.5-2027.7毕业，硕士及以上为主）"
    },
    {
      "id": "cms-2027",
      "org": "招商证券",
      "position": "2027届校园招聘（投行类 / 研究类 / 投资类 / 营销类 / IT类 / 博士后等7部门25岗位，约300人）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-07",
      "deadlineNote": "报名时间2026-09-07至2026-10-07 00:00；工作地点深圳/北京/上海/广州等近百城",
      "source": "招商证券招聘公众号 / cms.hotjob.cn",
      "publishedAt": "2026-09-07",
      "url": "https://cms.hotjob.cn",
      "target": "2027届"
    },
    {
      "id": "cssc-2027",
      "org": "中国船舶集团",
      "position": "2027届校园招聘（船舶与海洋工程 / 机械 / 电气 / 电子 / 计算机 / 人工智能 / 控制等研发与工程岗）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招已开启（网申系统 cssc.zhaopin.com / cssc.zhiye.com），招满即止；具体截止以官网为准",
      "source": "中国船舶招聘官网 / 国资委专栏 / 高校就业网",
      "publishedAt": "2026-08-17",
      "url": "https://cssc.zhaopin.com",
      "target": "2027届（硕士及以上为主）"
    },
    {
      "id": "aecc-2027",
      "org": "中国航空发动机集团（中国航发）",
      "position": "2027届校园招聘（航空发动机核心 / 绿色动力 / 适航 / 材料制造 / 智能控制 / 经营管理等，27家直属单位）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招已启动（网申 aecc.iguopin.com），招满即止；9-10月宣讲双选会密集（以官网为准）",
      "source": "中国航发招聘官网 aecc.iguopin.com / 国资委专栏",
      "publishedAt": "2026-09-01",
      "url": "https://aecc.iguopin.com",
      "target": "2027届（理工科为主，硕博优先）"
    },
    {
      "id": "crrc-2027",
      "org": "中国中车",
      "position": "2027届校园招聘（轨道交通研发 / 工艺 / 电气 / 软件 / 机械 / 供应链 / 职能管培等，本科至博士）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "集团统一正式批网申约2026年9月上旬启动、10月下旬关闭通道（预测，以官网为准）；提前批7-8月已收尾",
      "source": "中车招聘云平台 crrc.hotjob.cn / 国资委专栏",
      "publishedAt": "2026-09-01",
      "url": "https://crrc.hotjob.cn",
      "target": "2027届（本科/硕士/博士，部分一线岗大专）"
    },
    {
      "id": "zte-2027",
      "org": "中兴通讯",
      "position": "研发类（AI/算力硬件/芯片/6G/NTN/卫星通信/射频天线/光传输等）/ 营销类 / 供应链类 / 运营支撑类",
      "category": "互联网大厂",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "网申无明确截止，岗位招满即止，建议尽早投递（2027届校招已于2026年9月启动）",
      "source": "中兴通讯招聘官网 job.zte.com.cn / 武汉大学就业信息网",
      "publishedAt": "2026-09-01",
      "url": "https://job.zte.com.cn/",
      "target": "2027届（大陆2027.1.1-12.31；港澳台及海外2026.1.1-2027.12.31）"
    },
    {
      "id": "csair-2027",
      "org": "中国南方航空",
      "position": "飞行技术 / 机务维修 / 客舱服务 / 地面服务 / 运行指挥 / 信息技术 / 市场营销 / 财务管理 / 法律合规 / 人力资源等",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-31",
      "deadlineNote": "网申2026.9.1-10.31；笔试11月中旬，面试11月下旬-12月中旬",
      "source": "中国南方航空招聘网 job.csair.com / 今日头条校招整理",
      "publishedAt": "2026-09-01",
      "url": "https://job.csair.com/",
      "target": "2027届（2026.9-2027.8毕业）"
    },
    {
      "id": "ceair-2027",
      "org": "中国东方航空",
      "position": "机务工程 / 航务运控 / IT数字化 / 营销服务 / 职能管理 / 医学保障 / 燕计划管培生等",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-12-31",
      "deadlineNote": "网申预计2026年9月上旬-12月31日（预测，以官网为准）；面试滚动开展11月-次年1月",
      "source": "中国东方航空招聘官网 / 今日头条校招整理",
      "publishedAt": "2026-09-01",
      "url": "https://job.ceair.com",
      "target": "2027届（2027.7.31前取得学历学位）"
    },
    {
      "id": "cnooc-2027",
      "org": "中国海油",
      "position": "油气勘探开发 / 炼化生产 / 工程建设 / 数字化新能源 / 销售经营 / 综合职能 / 一线技能操作",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "网上报名预计2026年9月20日左右启动、持续至10月底（预测，以官网为准）；统一笔试约11月中旬",
      "source": "中国海油招聘官网 cnooc.zhaopin.com / 高顿·上岸鸭",
      "publishedAt": "",
      "url": "https://cnooc.zhaopin.com",
      "target": "2027届（含两年择业期内未就业）"
    },
    {
      "id": "cgn-2027",
      "org": "中广核",
      "position": "核电技术类 / 电气自动化与数字类（AI、网安）/ 机械材料土建类 / 综合职能类 / 核工程运行维修",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届秋招已启动（简历投递2026-09-04起，官网 cgn.hotjob.cn），招满即止；笔试约10月中旬（以官网为准）",
      "source": "中广核招聘 cgn.hotjob.cn / 北大就业网",
      "publishedAt": "2026-09-09",
      "url": "https://cgn.hotjob.cn",
      "target": "2027届（含2026届未就业；统招应届，本科≤25/硕士≤28/博士≤33）"
    },
    {
      "id": "chng-2027",
      "org": "中国华能",
      "position": "电力/能源（核电、新能源、火电等）/ 工程 / 职能（含华能核电专项、英才/优才管培）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届秋招已启动（集团官网9月中旬开放网申，持续至11月上旬；总部及在京单位网申截止约10-31，各子公司陆续截止，招满即止，以官网为准）",
      "source": "中国华能招聘 zhaopin.chng.com.cn / 高顿·上岸鸭",
      "publishedAt": "",
      "url": "https://zhaopin.chng.com.cn",
      "target": "2027届（2026届未就业亦可）"
    },
    {
      "id": "spic-2027",
      "org": "国家电投",
      "position": "核电/电力/新能源 / 工程 / 职能（含钍基核能科技等专项）",
      "category": "央国企",
      "batch": "正式批（预测）",
      "deadline": "",
      "deadlineNote": "网申约2026年9月17日开放（往年参照，预测，以官网为准）",
      "source": "国家电投招聘 / 瑞涯教育·上岸鸭",
      "publishedAt": "",
      "url": "https://www.spic.com.cn",
      "target": "2027届"
    },
    {
      "id": "crec-2027",
      "org": "中国中铁",
      "position": "工程技术 / 工程管理 / 造价 / 机械 / 安全 / 财会 / 职能（建筑基建央企）",
      "category": "央国企",
      "batch": "正式批（预测）",
      "deadline": "",
      "deadlineNote": "2027届校招预计2026年9-10月集中开启网申（预测，以官网为准）",
      "source": "中国中铁招聘 / 高校就业网 / 上岸鸭时间线",
      "publishedAt": "",
      "url": "https://www.crec.cn",
      "target": "2027届本科及以上"
    },
    {
      "id": "crcc-2027",
      "org": "中国铁建",
      "position": "工程技术 / 工程管理 / 造价 / 机械 / 安全 / 财会 / 职能（建筑基建央企）",
      "category": "央国企",
      "batch": "正式批（预测）",
      "deadline": "",
      "deadlineNote": "2027届校招预计2026年9-10月集中开启网申（预测，以官网为准）",
      "source": "中国铁建招聘 / 高校就业网 / 上岸鸭时间线",
      "publishedAt": "",
      "url": "https://www.crcc.cn",
      "target": "2027届本科及以上"
    },
    {
      "id": "avic-shanfei-2027",
      "org": "航空工业陕飞（陕西飞机工业）",
      "position": "2027届校园招聘（设计研发 / 工艺技术 / 信息化软件 / 质量适航测试 / 职能管理，本硕博）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招于2026年9月正式启动，经“航空工业陕飞”官方公众号投递，招满即止（以官方为准）",
      "source": "国资委人事招聘专栏 / 航空工业陕飞官微",
      "publishedAt": "2026-09-04",
      "url": "https://www.avic.com.cn",
      "target": "2027届（本/硕/博，理工科为主）"
    },
    {
      "id": "ceec-2027",
      "org": "中国能建",
      "position": "规划咨询 / 勘测设计 / 工程建设 / 装备制造 / 资本金融 / 国际业务 / 人工智能 / 数字信息 / 市场运营 / 通用职能（近1200岗位、5000+人）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2027-06-30",
      "deadlineNote": "网申2026.9-2027.6，招满即止（全球校招，覆盖100+城市及海外）",
      "source": "国聘网 / 中国能建招聘 ceec.iguopin.com",
      "publishedAt": "2026-09-09",
      "url": "https://ceec.iguopin.com/",
      "target": "2027届（国内外高校）"
    },
    {
      "id": "cam-2027",
      "org": "中国机械科学研究总院集团",
      "position": "2027届校园招聘（科研 / 工程 / 职能方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止（以官网为准）",
      "source": "国聘网 https://www.iguopin.com",
      "publishedAt": "2026-09-09",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "yalongjiang-2027",
      "org": "雅砻江水电",
      "position": "2027届校园招聘（水电 / 新能源 / 工程 / 职能方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "招满即止（以官网为准）",
      "source": "国聘网 https://www.iguopin.com",
      "publishedAt": "2026-09-09",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "guoxin-2027",
      "org": "中国国新",
      "position": "2027届校园招聘（投资 / 金融 / 综合职能方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-23",
      "deadlineNote": "网申截止2026-10-23（国聘网列名国脉新星计划，14家子企业）",
      "source": "国聘网 https://www.iguopin.com",
      "publishedAt": "2026-09-09",
      "url": "https://www.iguopin.com",
      "target": "2027届"
    },
    {
      "id": "cec-2027",
      "org": "中国电子",
      "position": "2027届校园招聘（集成电路 / 计算机 / 电子信息 / 自动化 / 软件 / 电气 / 经管 / 法学等，北京/上海/深圳/武汉/成都等10城）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招于2026-09-04正式启动，招满即止（以官网为准）",
      "source": "中国电子招聘 career.cec.com.cn / 国聘网",
      "publishedAt": "2026-09-04",
      "url": "https://career.cec.com.cn",
      "target": "2027届"
    },
    {
      "id": "cmg-2027",
      "org": "招商局集团",
      "position": "2027届全球校园招聘（交通物流 / 金融 / 船舶 / 生产运营 / 工程技术 / AI / 建筑设计 / 法务等多方向）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "各板块单位2026年9月上旬起陆续发布岗位，招满即止（以官网为准）",
      "source": "招商局集团招聘官网 / 国聘网",
      "publishedAt": "2026-09-01",
      "url": "https://www.cmhk.com",
      "target": "2027届"
    },
    {
      "id": "cssgc-2027",
      "org": "中国兵器装备集团",
      "position": "2027届校园招聘（军工研发 / 技术 / 制造方向，兵器工业+兵器装备联合秋招）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招于2026年9月联合启动，全年37场招聘会陆续开展，招满即止（以官网为准）",
      "source": "国务院国资委人事招聘专栏 / 国资小新 / 国聘网",
      "publishedAt": "2026-09-01",
      "url": "https://www.iguopin.com",
      "target": "2027届（理工科为主）"
    },
    {
      "id": "powerchina-2027",
      "org": "中国电建",
      "position": "2027届校园招聘（电气 / 能源动力 / 土木 / 新能源 / 机械 / 计算机 / 造价等，六险二金）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "下属各单位2026年9月1日起陆续启动网申，招满即止（以官网为准）",
      "source": "中国电建招聘 powerchina.cn / 高校就业网",
      "publishedAt": "2026-09-01",
      "url": "https://www.powerchina.cn",
      "target": "2027届本科及以上"
    },
    {
      "id": "catarc-2027",
      "org": "中汽中心（中国汽车技术研究中心）",
      "position": "2027届校园招聘（管理培训生 / 技术研发 / 检验认证 / 行业与政策研究 / 标准研究 / 咨询服务 / 市场营销 / 职能管理；车辆工程、AI、计算机、新能源等多专业）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招已于2026年9月全面启动（提前批+正式批），招满即止；网申 career.catarc.ac.cn（以官网为准）",
      "source": "中汽中心官微 / 国资小新 / 高校就业网（北理工、哈工大威海等）",
      "publishedAt": "2026-09-09",
      "url": "https://career.catarc.ac.cn",
      "target": "2027届（本科及以上）"
    },
    {
      "id": "mcc-2027",
      "org": "中国中冶（冶金科工集团）",
      "position": "2027届校园招聘（矿产资源开发 / 勘察设计 / 数智应用 / 新能源 / 特色基础设施 / 科技研发 / 工程管理；中冶武勘、中冶南方等子企业）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招已于2026年9月启动（中冶武勘9.4、中冶南方等陆续开），招满即止（以官网为准）",
      "source": "国家大学生就业服务平台 ncss.cn / 高校就业网 / 中冶官微",
      "publishedAt": "2026-09-04",
      "url": "https://www.mcc.com.cn",
      "target": "2027届（硕士及以上为主，部分本科）"
    },
    {
      "id": "cncec-2027",
      "org": "中国化学工程",
      "position": "2027届全球校园招聘（工艺研发 / 工程设计 / 项目管理 / 施工管理 / 实业运营 / 职能管理 / 市场营销 / 信息技术；33家二级企业）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届全球校招已于2026年9月启动（校园行9.8起多校宣讲），招满即止（以官网为准）",
      "source": "中国化学工程官微 / 高校就业网（北化工等） / 超级简历",
      "publishedAt": "2026-09-08",
      "url": "https://www.cncec.cn",
      "target": "2027届（国境外本科/硕士/博士）"
    },
    {
      "id": "baowu-2027",
      "org": "中国宝武",
      "position": "2027届校园招聘（计算机AI / 资源采矿 / 生产工艺 / 机械设备 / 国际贸易 / 财务 / 物流等；国宝生计划）",
      "category": "央国企",
      "batch": "正式批（预测）",
      "deadline": "",
      "deadlineNote": "2027届秋招预计2026年9-11月集中启动（宝钢股份提前批已开启，招满即止），以官网为准（预测）",
      "source": "中国宝武官网 baowugroup.com / 应届生求职网宣讲会 / 宝钢股份校招",
      "publishedAt": "",
      "url": "https://www.baowugroup.com",
      "target": "2027届（本科及以上）"
    },
    {
      "id": "spdb-2027",
      "org": "浦发银行",
      "position": "2027年度校园招聘（管理培训生 / 科技金融 / 业务储备生 / 科技储备生 / 综合运营；总分行多机构）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "2026-10-08",
      "deadlineNote": "网申2026.9.3 10:00-10.8 18:00；笔试10月中下旬，面试11月起（以官网为准）",
      "source": "浦发银行招聘官网 job.spdb.com.cn / 国家大学生就业服务平台 / 高校就业网",
      "publishedAt": "2026-09-03",
      "url": "https://job.spdb.com.cn",
      "target": "2027届（境内外2025.1.1-2027.7.31毕业，本科及以上）"
    },
    {
      "id": "harbin-electric-2027",
      "org": "哈尔滨电气集团（哈电集团）",
      "position": "2027届校园招聘（机械 / 电气 / 能源动力 / 自动化 / 材料 / 计算机 / 电子信息 / 水利水电 / 核科学 / 控制 / 船舶 / 力学 / 数学 / 管理 / 法学；核心子企业哈电电机厂、锅炉厂、汽轮机厂等）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招已于2026年9月启动（官网 hadian.zhaopin.com），招满即止；核心子企业哈尔滨电机厂简历投递至2027-07-31（以官网为准）",
      "source": "哈尔滨电气集团2027届校招简章 / 高校就业网（哈工大威海、厦大、西交等）",
      "publishedAt": "2026-09-01",
      "url": "https://hadian.zhaopin.com",
      "target": "2027届（含2026届未就业；本科/硕士/博士）"
    },
    {
      "id": "chinadatang-2027",
      "org": "中国大唐集团",
      "position": "2027届校园招聘（电力生产 / 新能源 / 储能 / 氢能 / 数字科技 / 金融环保 / 职能；43家二级单位、300余家基层企业）",
      "category": "央国企",
      "batch": "正式批（预测）",
      "deadline": "",
      "deadlineNote": "2027届秋招预计2026年9月下旬-10月下旬开放网申（预测，以官网为准）；优才提前批7-9月；官网 zhaopin.china-cdt.com",
      "source": "中国大唐集团招聘平台 zhaopin.china-cdt.com / 高顿·央国企 / 高校就业网",
      "publishedAt": "",
      "url": "https://zhaopin.china-cdt.com",
      "target": "2027届（2026.9-2027.8毕业，本科及以上；部分基层专科）"
    },
    {
      "id": "huadian-2027",
      "org": "中国华电集团",
      "position": "2027届校园招聘（电力生产运维 / 新能源 / 财务 / 项目前期；浙江等区域公司先行，集团统招随后）",
      "category": "央国企",
      "batch": "正式批（预测）",
      "deadline": "",
      "deadlineNote": "浙江等区域公司2027校招已于2026年9月启动宣讲网申；集团正式批预计2026年10月集中开放（预测，以官网为准）",
      "source": "中国华电集团浙江公司2027校招 / 高校就业网（浙大、大连理工、南开、武大等）",
      "publishedAt": "2026-09-02",
      "url": "https://www.chd.com.cn",
      "target": "2027届（海内外应届，本科及以上）"
    },
    {
      "id": "dongfang-electric-2027",
      "org": "中国东方电气集团",
      "position": "2027届校园招聘（研发 / 设计 / 工艺 / 试验 / 信息技术 / 营销 / 项目管理 / 采购 / 党建 / 人力 / 财务等；20+单位、400+岗位、900+offer）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招已正式开启（宣讲9.14起），网申招满即止；校招官网+东方电气微招聘公众号+国聘+智联多渠道投递（以官网为准）",
      "source": "东方电气微招聘 / 国聘 / 智联招聘 / 东方电气集团校招官网",
      "publishedAt": "2026-09-14",
      "url": "https://www.dongfang.com",
      "target": "2027届国内外高校毕业生（含2026届未就业）"
    },
    {
      "id": "crsc-2027",
      "org": "中国铁路通信信号集团（中国通号）",
      "position": "2027届校园招聘（研发 / 技术 / 管理 / 技能岗；轨道交通控制系统+低空经济方向，110+岗位）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届校招专区已开启（校招行程9.5起），网申招满即止；工作地点北京/上海/天津/西安/郑州/长沙/广州/沈阳/武汉等（以官网为准）",
      "source": "中国通号招聘平台 / 西安交大就业网 / 国聘",
      "publishedAt": "2026-09-05",
      "url": "https://www.crsc.com.cn",
      "target": "2027届（本科及以上，理工类为主）"
    },
    {
      "id": "pipechina-2027",
      "org": "国家石油天然气管网集团（国家管网）",
      "position": "2027届校园招聘（生产运行 / 工程技术 / 信息技术 / HSE / 经济管理 / 职能管理；油气储运、电气、机械、计算机等）",
      "category": "央国企",
      "batch": "正式批",
      "deadline": "",
      "deadlineNote": "2027届秋招9月启动，网申预计2026.9-10月中旬（部分来源称9.1-10.15，以官网为准）；每人最多投2家单位、每家限1岗；集团统一笔试约10月底",
      "source": "国家管网集团招聘 zhaopin.pipechina.com.cn / 应届生求职网 / 国聘",
      "publishedAt": "",
      "url": "https://zhaopin.pipechina.com.cn",
      "target": "2027届全日制（含2026届未就业）；本科CET4≥425、硕博CET6≥425"
    },
    {
      "id": "chalco-2027",
      "org": "中国铝业集团（中铝集团）",
      "position": "2027届校园招聘（技术 / 科研研发 / 工程技术 / 生产操作 / 职能管理；冶金、材料、地质、采矿、机电等）",
      "category": "央国企",
      "batch": "正式批（预测）",
      "deadline": "",
      "deadlineNote": "2027届秋招预计2026年9月底-10月初开启网申，各子公司截止不同、招满即止（预测，以官方公告为准）",
      "source": "中铝集团招聘公众号 / 国聘 / 高校就业网",
      "publishedAt": "",
      "url": "https://www.chinalco.com.cn",
      "target": "2027届（硕博优先，部分基层大专）"
    }
  ],
  "generatedAt": "2026-09-15T00:55:16.955Z"
};
